import { useState, useEffect } from "react";
import { useSearch, useNavigate } from "@tanstack/react-router";
import { Bookmark, BookmarkCheck, GitCompare, Eye, Scale, Search, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { usePrecedentSearch, usePrecedentSummary, useSavedPrecedents } from "./usePrecedents";
import { useCases } from "@/features/cases/useCases";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

function relevanceTone(score: number) {
  if (score >= 85) return "text-success";
  if (score >= 70) return "text-primary";
  return "text-muted-foreground";
}

function PrecedentCard({ 
  p, 
  search,
  saved, 
  toggle, 
  compare, 
  toggleCompare 
}: { 
  p: any; 
  search: string;
  saved: string[]; 
  toggle: (id: string) => void; 
  compare: string[]; 
  toggleCompare: (id: string) => void; 
}) {
  const isSaved = saved.includes(p.id);
  const inCompare = compare.includes(p.id);
  const [expanded, setExpanded] = useState(false);
  const { data, isLoading } = usePrecedentSummary(p.id, search, expanded, p.summary);

  return (
    <article
      className={cn("panel p-5 transition-colors", inCompare && "ring-1 ring-primary/40")}
    >
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <h2 className="font-display text-lg leading-snug font-semibold">{p.title}</h2>
          <p className="mt-1 text-xs text-muted-foreground">
            {p.court} {p.date ? `· ${p.date}` : ""}
          </p>
        </div>
        <div className="text-right">
          <p className={cn("font-display text-2xl font-semibold", relevanceTone(p.relevance))}>
            {p.relevance}%
          </p>
          <p className="text-[10px] tracking-wide text-muted-foreground uppercase">
            relevance
          </p>
        </div>
      </div>

      {!expanded ? (
        <div className="mt-3">
          <p className="text-sm leading-relaxed text-muted-foreground line-clamp-2">
            {p.summary}
          </p>
          <Button 
            variant="link" 
            className="h-auto p-0 text-xs mt-1"
            onClick={() => setExpanded(true)}
          >
            Generate AI Summary
          </Button>
        </div>
      ) : (
        <div className="mt-3 p-3 bg-secondary/30 rounded-md border text-sm leading-relaxed text-muted-foreground">
          {isLoading ? (
            <div className="space-y-2">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-[85%]" />
              <Skeleton className="h-4 w-[40%]" />
            </div>
          ) : data ? (
            <>
              <p>{data.aiSummary}</p>
              <div className="mt-2 flex justify-between items-center text-[10px] uppercase tracking-wider text-muted-foreground/70">
                <span>AI-generated by {data.provider}</span>
                <span className="text-warning font-semibold">⚠️ Verify before citing</span>
              </div>
            </>
          ) : (
            <p className="text-destructive">Failed to generate summary.</p>
          )}
        </div>
      )}

      <div className="mt-3 flex flex-wrap items-center gap-1.5">
        <Badge variant="outline">{p.outcome}</Badge>
      </div>

      <div className="mt-4 flex flex-wrap gap-2 border-t pt-3">
        <Button size="sm" variant="default" asChild>
          <a href={`https://indiankanoon.org/doc/${p.id}/`} target="_blank" rel="noopener noreferrer">
            <Eye className="mr-1.5 h-3.5 w-3.5" /> View on IK
          </a>
        </Button>
        <Button size="sm" variant="outline" onClick={() => toggle(p)}>
          {isSaved ? (
            <>
              <BookmarkCheck className="mr-1.5 h-3.5 w-3.5 text-primary" /> Saved
            </>
          ) : (
            <>
              <Bookmark className="mr-1.5 h-3.5 w-3.5" /> Save
            </>
          )}
        </Button>
        <Button
          size="sm"
          variant={inCompare ? "secondary" : "ghost"}
          onClick={() => toggleCompare(p.id)}
        >
          <GitCompare className="mr-1.5 h-3.5 w-3.5" />
          {inCompare ? "In comparison" : "Compare"}
        </Button>
      </div>
    </article>
  );
}

export default function PrecedentSearchPage() {
  const searchParams = useSearch({ strict: false });
  const navigate = useNavigate();
  const initialCaseId = (searchParams as any).caseId;
  const [selectedCaseId, setSelectedCaseId] = useState<string>(initialCaseId || "");
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [compare, setCompare] = useState<string[]>([]);
  
  const { items: cases, loading: casesLoading } = useCases({ pageSize: 100 });

  useEffect(() => {
    if (!selectedCaseId && cases.length > 0) {
      setSelectedCaseId(cases[0].id);
    }
  }, [cases, selectedCaseId]);

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearch(search);
    }, 500);
    return () => clearTimeout(handler);
  }, [search]);

  // Update URL when case changes to share links
  const handleCaseChange = (newCaseId: string) => {
    setSelectedCaseId(newCaseId);
    navigate({ search: { caseId: newCaseId }, replace: true });
  };

  // Passing the current context to usePrecedentSearch
  const { results, total, loading } = usePrecedentSearch({
    search: debouncedSearch,
    caseId: selectedCaseId,
  });
  const { saved, toggle } = useSavedPrecedents(selectedCaseId);

  const reset = () => {
    setSearch("");
    setDebouncedSearch("");
  };

  const toggleCompare = (id: string) =>
    setCompare((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : prev.length >= 3 ? prev : [...prev, id],
    );

  return (
    <div className="mx-auto max-w-[1400px] space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <p className="text-eyebrow">Research</p>
          <h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Legal precedent search</h1>
          <p className="mt-1.5 text-sm text-muted-foreground">
            Semantic search across reported judgments, ranked by relevance to the active matter.
          </p>
        </div>
        
        {/* Case Selector and IKanoon Powered By Logo */}
        <div className="flex flex-col items-end gap-3">
          <div className="w-full min-w-[250px]">
            <Select value={selectedCaseId} onValueChange={handleCaseChange}>
              <SelectTrigger className="h-9 text-sm bg-background">
                <SelectValue placeholder={casesLoading ? "Loading cases…" : "Choose a case"} />
              </SelectTrigger>
              <SelectContent>
                {cases.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.caseNumber ? `${c.caseNumber} — ` : ""}
                    {c.title}
                  </SelectItem>
                ))}
                {cases.length === 0 && !casesLoading && (
                  <SelectItem value="__none" disabled>
                    No cases found
                  </SelectItem>
                )}
              </SelectContent>
            </Select>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 bg-secondary/50 rounded-md w-fit">
            <span className="text-xs text-muted-foreground font-medium">Powered by</span>
            <span className="text-sm font-bold tracking-tight text-primary">IndianKanoon</span>
          </div>
        </div>
      </div>

      <div className="panel space-y-4 p-5 border-t-2 border-t-primary/20">
        <div className="relative">
          <Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by proposition, citation, judge or statute — e.g. “65B certificate call records”"
            className="h-11 pl-9"
          />
        </div>

        {search && (
          <div className="flex flex-wrap items-center gap-2 pt-1 text-xs text-muted-foreground">
            <Button variant="ghost" size="sm" onClick={reset} className="h-7 px-2">
              <X className="mr-1 h-3.5 w-3.5" /> Clear search
            </Button>
          </div>
        )}

        <div className="flex flex-wrap items-center justify-between gap-2 border-t pt-3 text-xs text-muted-foreground">
          <span>
            {loading ? "Searching…" : `${total} judgment${total === 1 ? "" : "s"} matched`}
          </span>
          {compare.length > 0 && (
            <span className="flex items-center gap-2">
              <Badge variant="secondary">{compare.length} selected to compare</Badge>
              <Button size="sm" variant="outline" className="h-7" disabled={compare.length < 2}>
                <GitCompare className="mr-1.5 h-3.5 w-3.5" /> Compare
              </Button>
            </span>
          )}
        </div>
      </div>

      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-40 w-full rounded-xl" />
          ))}
        </div>
      ) : results.length === 0 ? (
        <div className="panel flex flex-col items-center gap-2 p-12 text-center">
          <Scale className="h-8 w-8 text-muted-foreground" />
          <p className="text-sm font-medium">No judgments matched</p>
          <p className="text-xs text-muted-foreground">
            Try modifying your search keywords.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {results.map((p) => (
            <PrecedentCard 
              key={p.id} 
              p={p} 
              search={search}
              saved={saved} 
              toggle={toggle} 
              compare={compare} 
              toggleCompare={toggleCompare} 
            />
          ))}
        </div>
      )}
    </div>
  );
}
