"""Add UserProfile model

Revision ID: 4e930112307f
Revises: ecc807dca318
Create Date: 2026-10-03 16:44:11.934272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e930112307f'
down_revision: Union[str, None] = 'ecc807dca318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('bar_council_id', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('practice_areas', sa.JSON(), nullable=True),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('firm_role', sa.String(length=255), nullable=True),
    sa.Column('enrolment_year', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
