"""Add CaseReport model

Revision ID: d2d78b62920d
Revises: f7366e0797c1
Create Date: 2026-10-03 17:10:20.209692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d78b62920d'
down_revision: Union[str, None] = 'f7366e0797c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_reports',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reports_case_id'), 'case_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_reports_user_id'), 'case_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_reports_user_id'), table_name='case_reports')
    op.drop_index(op.f('ix_case_reports_case_id'), table_name='case_reports')
    op.drop_table('case_reports')
    # ### end Alembic commands ###
