"""initial_schema

Revision ID: e296563c56f1
Revises: 
Create Date: 2026-08-16 00:06:27.722263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e296563c56f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('LAWYER', 'PARALEGAL', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('court_name', sa.String(), nullable=True),
    sa.Column('judge_name', sa.String(), nullable=True),
    sa.Column('fir_number', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNDER_TRIAL', 'RESERVED_FOR_JUDGMENT', 'DISPOSED', 'STAYED', 'APPEAL_FILED', name='casestatus'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='casepriority'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('lead_counsel', sa.String(), nullable=True),
    sa.Column('statutes', sa.JSON(), nullable=True),
    sa.Column('filed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_court_name', 'cases', ['court_name'], unique=False)
    op.create_index('ix_cases_fir_number', 'cases', ['fir_number'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_index('ix_cases_user_id', 'cases', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING_OCR', 'PROCESSING_AI', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_case_id', 'documents', ['case_id'], unique=False)
    op.create_table('precedent_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('source_judgment_url', sa.String(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=True),
    sa.Column('judgment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('citation_status', sa.Enum('PARTY', 'NEUTRAL', 'POSITIVE', 'NEGATIVE', name='citationstatus'), nullable=False),
    sa.Column('query_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_precedent_results_case_id', 'precedent_results', ['case_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_chunks_doc_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_doc_chunks_vector_id', 'document_chunks', ['vector_id'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('JUDGE', 'WITNESS', 'PARTY', 'ADVOCATE', 'ACCUSED', 'LOCATION', 'STATUTE', 'DATE', 'ORGANIZATION', 'COURT', 'CASE_NUMBER', name='entitytype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('statute_framework', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_user_corrected', sa.Boolean(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_entities_doc_id', 'extracted_entities', ['document_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('source_doc_id', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('INCIDENT', 'ARREST', 'FILING', 'HEARING', 'ORDER', 'JUDGMENT', name='eventtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_user_corrected', sa.Boolean(), nullable=False),
    sa.Column('original_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_case_id', 'timeline_events', ['case_id'], unique=False)
    op.create_table('correction_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('extracted_entity_id', sa.String(), nullable=True),
    sa.Column('timeline_event_id', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extracted_entity_id'], ['extracted_entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corr_logs_extracted_entity_id', 'correction_logs', ['extracted_entity_id'], unique=False)
    op.create_index('ix_corr_logs_timeline_event_id', 'correction_logs', ['timeline_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_corr_logs_timeline_event_id', table_name='correction_logs')
    op.drop_index('ix_corr_logs_extracted_entity_id', table_name='correction_logs')
    op.drop_table('correction_logs')
    op.drop_index('ix_timeline_events_case_id', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_extracted_entities_doc_id', table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index('ix_doc_chunks_vector_id', table_name='document_chunks')
    op.drop_index('ix_doc_chunks_doc_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_precedent_results_case_id', table_name='precedent_results')
    op.drop_table('precedent_results')
    op.drop_index('ix_documents_case_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_cases_user_id', table_name='cases')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_fir_number', table_name='cases')
    op.drop_index('ix_cases_court_name', table_name='cases')
    op.drop_table('cases')
    op.drop_table('users')
    # ### end Alembic commands ###
