"""Add PrecedentResult

Revision ID: ecc807dca318
Revises: e296563c56f1
Create Date: 2026-10-03 04:53:32.278927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc807dca318'
down_revision: Union[str, None] = 'e296563c56f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precedent_results', sa.Column('precedent_id', sa.String(), nullable=False))
    op.create_index('ix_precedent_results_precedent_id', 'precedent_results', ['precedent_id'], unique=False)
    op.create_unique_constraint('uq_case_precedent', 'precedent_results', ['case_id', 'precedent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_case_precedent', 'precedent_results', type_='unique')
    op.drop_index('ix_precedent_results_precedent_id', table_name='precedent_results')
    op.drop_column('precedent_results', 'precedent_id')
    # ### end Alembic commands ###
